FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase
    Walk:
      id: 4 
      type: RLBase
<<<<<<< HEAD
    Walk_realsense:
=======

    WalkPro:
>>>>>>> a5cd658 (更新G1机器人的状态机配置，移除盲行模式并添加WalkPro状态)
      id: 5
      type: RLBase

    Mimic_Dance1_subject2:
      id: 6
      type: Mimic

    mengguwu:
      id: 7
      type: Mimic


  Passive:
    transitions: 
      FixStand: LT + up.on_pressed
    mode: [
      1,1,1,1,1,1,
      1,1,1,1,1,1,
      1,1,1,
      1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,
    ]
    kd: [
      3,3,3,3,3,3,
      3,3,3,3,3,3,
      3,3,3,
      3,3,3,3,3,3,3,  
      3,3,3,3,3,3,3,  
    ]


  FixStand:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RT + A.on_pressed
      Walk: RT + B.on_pressed
<<<<<<< HEAD
      Walk_realsense: RT + Y.on_pressed
=======
      WalkPro: RT + Y.on_pressed
>>>>>>> a5cd658 (更新G1机器人的状态机配置，移除盲行模式并添加WalkPro状态)

    kp: [
      100,100,100,150,40,40,
      100,100,100,150,40,40,
      200,200,200,
      40,40,40,40,40,40,40,
      40,40,40,40,40,40,40,
    ]
    kd: [
      2,2,2,4,2,2,
      2,2,2,4,2,2,
      5,5,5,
      10,10,10,10,10,10,10,
      10,10,10,10,10,10,10,
    ]
    ts: [0, 2]
    qs: [
      [],
      [ -0.1, 0,0,0.3,-0.2,0,
        -0.1, 0,0,0.3,-0.2,0,
        0,0,0,
        0.35, 0.18,0,0.87,0,0,0,
        0.35,-0.18,0,0.87,0,0,0
      ]
    ]


  Velocity:
    transitions: 
      Passive: LT + B.on_pressed
      Mimic_Dance1_subject2: RB + A.on_pressed

    policy_dir: config/policy/velocity

  Walk:
      transitions: 
        Passive: LT + B.on_pressed
        Mimic_Dance1_subject2: RB + A.on_pressed
        mengguwu: RB + X.on_pressed

      policy_dir: config/policy/walk

  WalkPro:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RT + A.on_pressed
      Walk: RT + B.on_pressed
    policy_dir: config/policy/walkpro

  # Blind:
  #     transitions:
  #       Passive: LT + B.on_pressed
  #       Mimic_Dance1_subject2: RB + A.on_pressed

  #     policy_dir: config/policy/blind

  Mimic_Dance1_subject2:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RT + A.on_pressed
      Walk: RT + B.on_pressed
    motion_file: config/policy/mimic/dance1_subject2/params/dance1_subject2.npz
    policy_dir: config/policy/mimic/dance1_subject2/
    time_start: 0.0
    time_end: 1000.0
    end_state: Walk

  mengguwu:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RT + A.on_pressed
      Walk: RT + B.on_pressed

    motion_file: config/policy/mimic/mengguwu/params/mengguwu.npz
    policy_dir: config/policy/mimic/mengguwu/
    time_start: 0.0
    time_end: 1000.0
    end_state: Walk

